name: flutter_map_eval
description: "Dart Eval bindings for map-related packages"
version: 0.0.1
homepage: https://github.com/zverik/flutter_map_eval

environment:
  sdk: ^3.9.2
  flutter: "^3.29.0"

dependencies:
  flutter:
    sdk: flutter
  dart_eval: ^0.8.1
  flutter_eval: ^0.8.1
  flutter_map: ^8.2.0
  flutter_map_geojson2: ^1.0.0
  adaptive_dialog: ^2.4.2
  http: ^1.6.0
  latlong2: ^0.9.0
  logging: ^1.3.0
  responsive_grid_list: ^1.2.3
  share_plus: ^11.0.0
  sqflite: ^2.4.2
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.0

dependency_overrides:
  flutter_eval:
    git:
      url: https://github.com/Zverik/flutter_eval.git
      ref: no_icons
